package net.sourceforge.pmd.cpd.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class ConnectionProxy implements IConnectionProxy {
	Connection conn;
	
	public ConnectionProxy(Connection conn) {
		this.conn = conn;
	}

	@Override
	public void commit() throws SQLException {
		conn.commit();
	}
	
	@Override
	public void rollback() throws SQLException {
		conn.rollback();
	}
	
	@Override
	public void closeConnection() {
		DbUtils.closeConnection(conn);
	}

	@Override
	public PreparedStatement prepareStatement(String sql) throws SQLException {
		return conn.prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		return conn.prepareStatement(sql, autoGeneratedKeys);
	}

	@Override
	public void close() throws SQLException {
		closeConnection();
	}
}
