package net.sourceforge.pmd.cpd.db;

import java.sql.PreparedStatement;
import java.sql.SQLException;


public interface IConnectionProxy extends AutoCloseable {
	void commit() throws SQLException;
	
	void rollback() throws SQLException;
	
	void close() throws SQLException;
	
	void closeConnection();
	
	PreparedStatement prepareStatement(String sql)
		        throws SQLException;
	
	PreparedStatement prepareStatement(String sql, int autoGeneratedKeys)
	        throws SQLException;
}
